spring.application.name=todo
#Configuracao da conexao com Banco de Dados

#Link de conexao com o banco de dados
spring.datasource.url = jdbc:h2:mem:tododb
#Selecao do Driver para comunicacao
spring.datasource.driverClassName=org.h2.Driver
#Criacao o usuario que realizara as interacoes com o banco de dados
spring.datasource.username=sa
#Senha de acesso ao Banco de Dados
spring.datasource.password=


#Confirguracao dop Hibernate/JPA para criacao automatica das tabelas
#Selecionando o dialeto correto para a criacao das requisicoes SQL
spring.jpa.database-plataform=org.hibernate.dialect.H2Dialect
#Permissao de acesso do hibernate para interacao com Banco de Dados
spring.jpa.hibernate.ddl-auto=update
#Apenas para desenvolvimento ->Requisicoes SQL serao mostradas no Console do Spring Boot
spring.jpa.show-sql=true

#Configuracao do h2 console -> Acesso remoto ao banco de dados

#Habilitar a conexao remota
spring.h2.console.enabled=true

#Criar o caminho de comunicacao
spring.h2.console.path=/h2-console

#